quarkus.http.port=8081

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${MOMENTS_DB_USERNAME:moments}
quarkus.datasource.password=${MOMENTS_DB_PASSWORD:moments}
quarkus.datasource.jdbc.url=${MOMENTS_DB_URL:jdbc:postgresql://localhost:5432/moments}

%dev.quarkus.hibernate-orm.schema-management.strategy=none
quarkus.flyway.migrate-at-start=true
